// <auto-generated />
using System;
using GeekSeo.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekSeo.Persistence.Migrations
{
    [DbContext(typeof(SeoDbContext))]
    [Migration("20260531155403_AddContentGuardTables")]
    partial class AddContentGuardTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("geek_seo")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("seo_alerts", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("seo_api_keys", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoBackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("seo_background_jobs", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoBrandVoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SampleText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StyleInstructions")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("seo_brand_voices", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoBulkJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("seo_bulk_jobs", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoCannibalizationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompetingUrlsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("seo_cannibalization_issues", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoCompetitorPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CrawledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExternalLinkCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasStructuredData")
                        .HasColumnType("boolean");

                    b.Property<string>("HeadingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ImageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ImagesMissingAlt")
                        .HasColumnType("integer");

                    b.Property<int>("InternalLinkCount")
                        .HasColumnType("integer");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("text");

                    b.Property<Guid>("SerpResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("StructuredDataTypesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TermsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SerpResultId", "Url")
                        .IsUnique();

                    b.ToTable("seo_competitor_pages", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoContentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("AiDetectionScore")
                        .HasColumnType("numeric");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastScoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PublishedScore")
                        .HasColumnType("integer");

                    b.Property<int?>("PublishedWordCount")
                        .HasColumnType("integer");

                    b.Property<string>("ScoreComponentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeoScore")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetKeyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("seo_content_documents", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoContentGuardPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoPatch")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("seo_content_guard_policies", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoContentGuardRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatchedHtml")
                        .HasColumnType("text");

                    b.Property<string>("PrePatchHtml")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublishedPageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WordPressDraftPostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("seo_content_guard_runs", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoContentPerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<decimal>("Ctr")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Position")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PublishedPageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PublishedPageId", "Date")
                        .IsUnique();

                    b.ToTable("seo_content_performance_snapshots", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoGa4Connection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptionIv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptionTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("seo_ga4_connections", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoGeoMentionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Mentioned")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QueryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Snippet")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QueryId");

                    b.ToTable("seo_geo_mention_snapshots", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoGeoTrackingQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("seo_geo_tracking_queries", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoGscConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptionIv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptionTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("seo_gsc_connections", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Intent")
                        .HasColumnType("text");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("KeywordDifficulty")
                        .HasColumnType("numeric");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SearchVolume")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("seo_keywords", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoKeywordCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AverageDifficulty")
                        .HasColumnType("numeric");

                    b.Property<int>("AverageVolume")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PillarKeyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("seo_keyword_clusters", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("seo_organizations", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoOrganizationMember", b =>
                {
                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrgId", "UserId");

                    b.ToTable("seo_organization_members", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoPageAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AuditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("seo_page_audits", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoPlagiarismCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MatchPercent")
                        .HasColumnType("numeric");

                    b.Property<string>("MatchesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("seo_plagiarism_checks", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("GscConnected")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("UserId");

                    b.ToTable("seo_projects", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoPublishedPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastAuditAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetKeyword")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WordPressPostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Url")
                        .IsUnique();

                    b.ToTable("seo_published_pages", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoRankTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<decimal>("Ctr")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Impressions")
                        .HasColumnType("integer");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Position")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("seo_rank_tracking", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("seo_reports", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoSerpDeepCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TermMatrixJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Keyword", "Location", "ResultCount")
                        .IsUnique();

                    b.ToTable("seo_serp_deep_cache", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoSerpResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeaturedSnippet")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeopleAlsoAskJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedSearchesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerpFeaturesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Keyword", "Location", "LanguageCode")
                        .IsUnique();

                    b.ToTable("seo_serp_results", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoSiteAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("numeric");

                    b.Property<int>("PagesCrawled")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("seo_site_audits", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoSiteAuditPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CrawledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("SiteAuditId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteAuditId");

                    b.ToTable("seo_site_audit_pages", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoSitePageInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CrawledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("H1")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Url")
                        .IsUnique();

                    b.ToTable("seo_site_page_inventory", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaypalSubscriptionId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("seo_subscriptions", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoTopicalMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClustersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentGapsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("seo_topical_maps", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoUsageCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PeriodStart", "Feature")
                        .IsUnique();

                    b.ToTable("seo_usage_counters", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoWordPressConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultPostStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("EncryptedAppPassword")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptionIv")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptionTag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("seo_wordpress_connections", "geek_seo");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoCompetitorPage", b =>
                {
                    b.HasOne("GeekSeo.Persistence.Entities.SeoSerpResult", "SerpResult")
                        .WithMany("CompetitorPages")
                        .HasForeignKey("SerpResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerpResult");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoContentDocument", b =>
                {
                    b.HasOne("GeekSeo.Persistence.Entities.SeoProject", "Project")
                        .WithMany("ContentDocuments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoContentPerformanceSnapshot", b =>
                {
                    b.HasOne("GeekSeo.Persistence.Entities.SeoPublishedPage", "PublishedPage")
                        .WithMany()
                        .HasForeignKey("PublishedPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublishedPage");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoGeoMentionSnapshot", b =>
                {
                    b.HasOne("GeekSeo.Persistence.Entities.SeoGeoTrackingQuery", "Query")
                        .WithMany("Snapshots")
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Query");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoOrganizationMember", b =>
                {
                    b.HasOne("GeekSeo.Persistence.Entities.SeoOrganization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoProject", b =>
                {
                    b.HasOne("GeekSeo.Persistence.Entities.SeoOrganization", null)
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoSiteAuditPage", b =>
                {
                    b.HasOne("GeekSeo.Persistence.Entities.SeoSiteAudit", "SiteAudit")
                        .WithMany("Pages")
                        .HasForeignKey("SiteAuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteAudit");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoGeoTrackingQuery", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoOrganization", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoProject", b =>
                {
                    b.Navigation("ContentDocuments");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoSerpResult", b =>
                {
                    b.Navigation("CompetitorPages");
                });

            modelBuilder.Entity("GeekSeo.Persistence.Entities.SeoSiteAudit", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
