// <auto-generated />
using ContentWriter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ContentWriter.Infrastructure.Migrations
{
    [DbContext(typeof(ContentWriterDbContext))]
    [Migration("20260713134500_AddDepartmentListExcerpt")]
    partial class AddDepartmentListExcerpt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
