// <auto-generated />
using System;
using ContentWriter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentWriter.Infrastructure.Migrations
{
    [DbContext(typeof(ContentWriterDbContext))]
    [Migration("20260712182308_AddGeneratedContentPresentationAndPublications")]
    partial class AddGeneratedContentPresentationAndPublications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content_writer")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentWriter.Domain.Entities.ContentFigure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BriefText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeekApiSlug")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("GeekPostId")
                        .HasColumnType("integer");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("HeadingSlug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImagePromptContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageRelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ImageStorage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("integer");

                    b.Property<bool>("NeedsFigureMerge")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("SectionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImagePromptContentId");

                    b.HasIndex("ProjectId", "SourceType", "HeadingSlug")
                        .IsUnique();

                    b.HasIndex("ProjectId", "SourceType", "SectionOrder");

                    b.ToTable("ContentFigures", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.CrawledSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CrawledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedFocus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedTone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JsonLdBlocks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagesCrawled")
                        .HasColumnType("integer");

                    b.Property<string>("Paragraphs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("CrawledSites", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.GeneratedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvertisingExcerpt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayTitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("GeneratedByModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GeneratedByProvider")
                        .HasColumnType("integer");

                    b.Property<string>("HeroImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("JsonLdSchema")
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingExcerpt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedArticleUrl")
                        .HasColumnType("text");

                    b.Property<string>("SectionOutline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SourceAppName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("SourceAppOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("GeneratedContents", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.KeywordSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ExtractedHeadings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedParagraphs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedQuestions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedTitle")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("KeywordSources", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PreferredProvider")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetKeyword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Projects", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.ProjectPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<string>("GeekApiSlug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("GeekPostId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ContentType", "GeekApiSlug")
                        .IsUnique();

                    b.ToTable("ProjectPublications", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.ContentFigure", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.GeneratedContent", "ImagePromptContent")
                        .WithMany()
                        .HasForeignKey("ImagePromptContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImagePromptContent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.CrawledSite", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithOne("CrawledSite")
                        .HasForeignKey("ContentWriter.Domain.Entities.CrawledSite", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.GeneratedContent", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithMany("GeneratedContents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.KeywordSource", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithMany("KeywordSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.ProjectPublication", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithMany("Publications")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.Project", b =>
                {
                    b.Navigation("CrawledSite");

                    b.Navigation("GeneratedContents");

                    b.Navigation("KeywordSources");

                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
