// <auto-generated />
using System;
using ContentWriter.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentWriter.Infrastructure.Migrations
{
    [DbContext(typeof(ContentWriterDbContext))]
    partial class ContentWriterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content_writer")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentWriter.Domain.Entities.CrawledSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CrawledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedFocus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedTone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JsonLdBlocks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagesCrawled")
                        .HasColumnType("integer");

                    b.Property<string>("Paragraphs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("CrawledSites", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.GeneratedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedByModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GeneratedByProvider")
                        .HasColumnType("integer");

                    b.Property<string>("JsonLdSchema")
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedArticleUrl")
                        .HasColumnType("text");

                    b.Property<string>("SectionOutline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("GeneratedContents", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.KeywordSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ExtractedHeadings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedParagraphs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedQuestions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedTitle")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("KeywordSources", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PreferredProvider")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetKeyword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Projects", "content_writer");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.CrawledSite", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithOne("CrawledSite")
                        .HasForeignKey("ContentWriter.Domain.Entities.CrawledSite", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.GeneratedContent", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithMany("GeneratedContents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.KeywordSource", b =>
                {
                    b.HasOne("ContentWriter.Domain.Entities.Project", "Project")
                        .WithMany("KeywordSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContentWriter.Domain.Entities.Project", b =>
                {
                    b.Navigation("CrawledSite");

                    b.Navigation("GeneratedContents");

                    b.Navigation("KeywordSources");
                });
#pragma warning restore 612, 618
        }
    }
}
