using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ContentWriterV3.Infrastructure.Data;

namespace ContentWriterV3.Infrastructure.Migrations
{
    [DbContext(typeof(ContentWriterV3DbContext))]
    partial class ContentWriterV3DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content_writer_v3")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a simplified snapshot. In production, this would be generated by EF Core.
#pragma warning restore 612, 618
        }
    }
}
