// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SiteAnalyzer2.Infrastructure.Persistence;

#nullable disable

namespace SiteAnalyzer2.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628134544_ModernizeAnalysisRunStatuses")]
    partial class ModernizeAnalysisRunStatuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sa2")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.AnalysisRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompetitorCrawlFinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompetitorCrawlMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("CompetitorCrawlStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompetitorCrawlStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GapTopics")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IncludeReferenceDomains")
                        .HasColumnType("boolean");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MatchedPillarAngle")
                        .HasColumnType("text");

                    b.Property<string>("MatchedPillarIntent")
                        .HasColumnType("text");

                    b.Property<string>("MatchedPillarTopic")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SerpCapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerpCheckUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("SerpClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SerpDepth")
                        .HasColumnType("integer");

                    b.Property<string>("SerpDevice")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SerpItemTypesJson")
                        .HasColumnType("text");

                    b.Property<int>("SerpItemsCount")
                        .HasColumnType("integer");

                    b.Property<string>("SerpLanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("SerpLocalPackPresent")
                        .HasColumnType("boolean");

                    b.Property<int?>("SerpLocationCode")
                        .HasColumnType("integer");

                    b.Property<int>("SerpMaxPage")
                        .HasColumnType("integer");

                    b.Property<string>("SerpOs")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SerpPagesCount")
                        .HasColumnType("integer");

                    b.Property<string>("SerpProviderKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SerpRefinementChipsJson")
                        .HasColumnType("text");

                    b.Property<string>("SerpSeDomain")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("SerpSeResultsCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("SerpShoppingResultsPresent")
                        .HasColumnType("boolean");

                    b.Property<string>("SerpSpellJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetSiteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("WritingInstructions")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("analysis_runs", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.ComparisonCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FindingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("comparison_checks", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorCrawlProgressLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Id");

                    b.ToTable("competitor_crawl_progress_logs", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CrawledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepthFromSeed")
                        .HasColumnType("integer");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FetchMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("SeedRankAbsolute")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("RunId", "Domain");

                    b.ToTable("competitor_pages", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorPageHeading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitorPageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorPageId");

                    b.ToTable("competitor_page_headings", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorPageJsonLd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitorPageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParsedType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorPageId");

                    b.ToTable("competitor_page_json_ld", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorPageMetaTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitorPageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameOrProperty")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompetitorPageId");

                    b.ToTable("competitor_page_meta_tags", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorSeedDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("competitor_seed_domains", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CrawlPriorityUrlPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Pattern")
                        .IsUnique();

                    b.ToTable("crawl_priority_url_patterns", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CrossRunLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromPageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsInternalToDomain")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToPageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromPageId");

                    b.HasIndex("RunId");

                    b.HasIndex("ToPageId");

                    b.ToTable("cross_run_links", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FindingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("findings", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.InternalLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnchorText")
                        .HasColumnType("text");

                    b.Property<Guid>("FromPageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToPageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromPageId");

                    b.HasIndex("RunId");

                    b.HasIndex("ToPageId");

                    b.ToTable("internal_links", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.KnownPlatformDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("known_platform_domains", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalUrl")
                        .HasColumnType("text");

                    b.Property<int?>("DepthFromHomepage")
                        .HasColumnType("integer");

                    b.Property<string>("FetchMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTargetSite")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RunId");

                    b.ToTable("pages", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageContentBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("page_content_blocks", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageHeading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("page_headings", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageJsonLd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParsedType")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("page_json_ld", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageMetaTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameOrProperty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("page_meta_tags", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageRankScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GraphScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("RunId");

                    b.ToTable("page_rank_scores", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxCrawlDepth")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCrawlPages")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("projects", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.ProjectOwnedDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_owned_domains", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.ReferenceExcludeDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("reference_exclude_domains", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.RunGate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RowCountsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ValidationMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("run_gates", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AboutThisResultJson")
                        .HasColumnType("text");

                    b.Property<bool>("Ads")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AiOverviewAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("AiOverviewMarkdown")
                        .HasColumnType("text");

                    b.Property<string>("AiOverviewStatusMessage")
                        .HasColumnType("text");

                    b.Property<bool>("AmpVersion")
                        .HasColumnType("boolean");

                    b.Property<string>("Breadcrumb")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("CacheUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExcludeReason")
                        .HasColumnType("text");

                    b.Property<string>("ExtendedPeopleAlsoSearchJson")
                        .HasColumnType("text");

                    b.Property<string>("ExtendedSnippet")
                        .HasColumnType("text");

                    b.Property<string>("FaqJson")
                        .HasColumnType("text");

                    b.Property<string>("FilterStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Filtered")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagesJson")
                        .HasColumnType("text");

                    b.Property<string>("IncludeReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsFeaturedSnippet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMalicious")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWebStory")
                        .HasColumnType("boolean");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PreSnippet")
                        .HasColumnType("text");

                    b.Property<string>("PriceJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("RankAbsolute")
                        .HasColumnType("integer");

                    b.Property<int>("RankGroup")
                        .HasColumnType("integer");

                    b.Property<string>("RatingJson")
                        .HasColumnType("text");

                    b.Property<string>("RectangleJson")
                        .HasColumnType("text");

                    b.Property<string>("RelatedResultJson")
                        .HasColumnType("text");

                    b.Property<string>("RelatedSearchUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("WebsiteName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Xpath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RunId", "RankAbsolute");

                    b.HasIndex("RunId", "Type");

                    b.ToTable("serp_items", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpItemHighlighted", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SerpItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("SerpItemId");

                    b.ToTable("serp_item_highlighted", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpItemLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SerpItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("SerpItemId");

                    b.ToTable("serp_item_links", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpRankSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ImportSequence")
                        .HasColumnType("integer");

                    b.Property<int>("OrganicResultCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SerpCapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TargetOrganicPosition")
                        .HasColumnType("integer");

                    b.Property<string>("TargetOrganicUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RunId", "ImportSequence")
                        .IsUnique();

                    b.ToTable("serp_rank_snapshots", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpRelatedQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SerpItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SerpItemId", "Sequence");

                    b.ToTable("serp_related_queries", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SiteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityPageUrls")
                        .HasColumnType("jsonb");

                    b.Property<string>("BusinessDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BusinessProfileAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BusinessSummary")
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CompetitorDomains")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("GeekSeoProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeneratedSchemaJson")
                        .HasColumnType("text");

                    b.Property<string>("GeoAnchorNodes")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NicheDescription")
                        .HasColumnType("text");

                    b.Property<string>("NicheTags")
                        .HasColumnType("jsonb");

                    b.Property<string>("PrimaryNiche")
                        .HasColumnType("text");

                    b.Property<string>("ServiceAreaDescription")
                        .HasColumnType("text");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WritingRecommendations")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GeekSeoProjectId");

                    b.HasIndex("SiteUrl")
                        .IsUnique();

                    b.ToTable("site_profiles", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.TargetSiteBusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("ExistingSchemaMatches")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedSchemaJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasExistingSchema")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryServicesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReusedFromRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceArea")
                        .HasColumnType("text");

                    b.Property<string>("TargetSiteUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.HasIndex("ProjectId", "TargetSiteUrl");

                    b.ToTable("target_site_business_profiles", "sa2");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.AnalysisRun", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Project", "Project")
                        .WithMany("Runs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.ComparisonCheck", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.AnalysisRun", "Run")
                        .WithMany("ComparisonChecks")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorPage", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.AnalysisRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorPageHeading", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.CompetitorPage", "Page")
                        .WithMany("Headings")
                        .HasForeignKey("CompetitorPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorPageJsonLd", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.CompetitorPage", "Page")
                        .WithMany("JsonLdBlocks")
                        .HasForeignKey("CompetitorPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorPageMetaTag", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.CompetitorPage", "Page")
                        .WithMany("MetaTags")
                        .HasForeignKey("CompetitorPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorSeedDomain", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Project", "Project")
                        .WithMany("CompetitorSeeds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CrossRunLink", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Page", "FromPage")
                        .WithMany()
                        .HasForeignKey("FromPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteAnalyzer2.Domain.Entities.Page", "ToPage")
                        .WithMany()
                        .HasForeignKey("ToPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromPage");

                    b.Navigation("ToPage");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.Finding", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.AnalysisRun", "Run")
                        .WithMany("Findings")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.InternalLink", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Page", "FromPage")
                        .WithMany()
                        .HasForeignKey("FromPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteAnalyzer2.Domain.Entities.Page", "ToPage")
                        .WithMany()
                        .HasForeignKey("ToPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromPage");

                    b.Navigation("ToPage");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.Page", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.AnalysisRun", "Run")
                        .WithMany("Pages")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageContentBlock", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Page", "Page")
                        .WithMany("ContentBlocks")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageHeading", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Page", "Page")
                        .WithMany("Headings")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageJsonLd", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Page", "Page")
                        .WithMany("JsonLdBlocks")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageMetaTag", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Page", "Page")
                        .WithMany("MetaTags")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.PageRankScore", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Page", "Page")
                        .WithMany("PageRankScores")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.ProjectOwnedDomain", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Project", "Project")
                        .WithMany("OwnedDomains")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.RunGate", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.AnalysisRun", "Run")
                        .WithMany("RunGates")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpItem", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.AnalysisRun", "Run")
                        .WithMany("SerpItems")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpItemHighlighted", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.SerpItem", "SerpItem")
                        .WithMany("HighlightedPhrases")
                        .HasForeignKey("SerpItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerpItem");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpItemLink", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.SerpItem", "SerpItem")
                        .WithMany("Links")
                        .HasForeignKey("SerpItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerpItem");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpRelatedQuery", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.SerpItem", "SerpItem")
                        .WithMany("RelatedQueries")
                        .HasForeignKey("SerpItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerpItem");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SiteProfile", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.Project", "GeekSeoProject")
                        .WithMany()
                        .HasForeignKey("GeekSeoProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GeekSeoProject");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.TargetSiteBusinessProfile", b =>
                {
                    b.HasOne("SiteAnalyzer2.Domain.Entities.AnalysisRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.AnalysisRun", b =>
                {
                    b.Navigation("ComparisonChecks");

                    b.Navigation("Findings");

                    b.Navigation("Pages");

                    b.Navigation("RunGates");

                    b.Navigation("SerpItems");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.CompetitorPage", b =>
                {
                    b.Navigation("Headings");

                    b.Navigation("JsonLdBlocks");

                    b.Navigation("MetaTags");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.Page", b =>
                {
                    b.Navigation("ContentBlocks");

                    b.Navigation("Headings");

                    b.Navigation("JsonLdBlocks");

                    b.Navigation("MetaTags");

                    b.Navigation("PageRankScores");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.Project", b =>
                {
                    b.Navigation("CompetitorSeeds");

                    b.Navigation("OwnedDomains");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("SiteAnalyzer2.Domain.Entities.SerpItem", b =>
                {
                    b.Navigation("HighlightedPhrases");

                    b.Navigation("Links");

                    b.Navigation("RelatedQueries");
                });
#pragma warning restore 612, 618
        }
    }
}
